name: Develop

on:
  push:
    branches:
      - "develop"
    paths-ignore:
      - "LICENSE"
      - "*.md"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Project Files
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Snyk client
      run: wget https://github.com/snyk/snyk/releases/download/v1.530.0/snyk-linux; mv ./snyk-linux ./snyk; chmod +x ./snyk;

    - name: Set up Compile, Build and Test environment
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Compile, Build and Test
      run: ./build.sh
      
    - name: Code Analysis - SAST (White-box testing)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./codeAnalysis.sh

    - name: Libraries Analysis - SAST (White-box testing)
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: ./librariesAnalysis.sh

    - name: Packaging
      run: ./package.sh

    - name: Package Analysis - SAST (White-box testing)
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: ./packageAnalysis.sh

  success-notification:
    if: success()
    name: success-notification
    needs: [run]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - uses: reside-eng/workflow-status-notification-action@v1.0.0
        with:
          #slack-message: Success !!!
          current-status: "success"
          slack-webhook: "${{ secrets.SLACK_WEBHOOK }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  failure-notification:
    if: failure()
    name: failure-notification
    needs: [run]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
      - uses: reside-eng/workflow-status-notification-action@v1.0.0
        with:
          #slack-message: Failed !!!
          current-status: "failure"
          slack-webhook: "${{ secrets.SLACK_WEBHOOK }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"