name: New features

on:
  push:
    branches:
      - "feature/*"
    paths-ignore:
      - "LICENSE"
      - "*.md"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Project Files
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Compile, Build and Test environment
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Compile, Build and Test
      run: ./build.sh
      
  success-notification:
    if: success()
    name: success-notification
    needs: [run]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - uses: reside-eng/workflow-status-notification-action@v1.0.0
        with:
          #slack-message: Success !!!
          current-status: "success"
          slack-webhook: "${{ secrets.SLACK_WEBHOOK }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  failure-notification:
    if: failure()
    name: failure-notification
    needs: [run]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
      - uses: reside-eng/workflow-status-notification-action@v1.0.0
        with:
          #slack-message: Failed !!!
          current-status: "failure"
          slack-webhook: "${{ secrets.SLACK_WEBHOOK }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"