name: ci

on:
  push:
    branches: feature
    paths-ignore:
      - "LICENSE"
      - "*.md"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Set up Project Files
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - 
        name: Set up Compile, Build and Test environment
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - 
        name: Compile, Build and Test
        run: ./build.sh       
      - 
        name: Publishing
#        env:
#         DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
#         DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
#         DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_USERNAME }}
#         DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker-compose -f ./iac/docker-compose.yml push        
